### ISSUE TITLE
IIIF Server setup

### ISSUE THREAD

**Issue by jtstratford** [ewg118/numishare#97] opened 2020-08-15 18:51 UTC
We are setting up Canteloupe as the IIIF Image Server.  Your default in the General Settings for Numishare is /usr/local/projects/numishare.  What is best practice for the image location?  Do you recommend a subfolder on that path for images or some other location?

Thanks again for all your help on this install.

**Comment by ewg118** [comment] 2020-08-17 13:58
Are you using the Numishare back-end to upload the images?

**Comment by jtstratford** [comment] 2020-08-17 20:26
We are trying to attach images to the numishare records on our local server.

When we import records from Mantis that have images attached, the URI's appear in the Digital Representations menu screen. However, when we try to attach local images or add URI's to imported records, we are not seeing any boxes on the Digital Representations menu screen. 

We are running Cantaloupe as web service under Tomcat 8.5. We have created a directory for images under /usr/local/projects/numishare belonging to tomcat with rwx permissions for all users. And we have been able to verify that Cantaloupe is functioning properly.

When we try to add images using the Digital Representations menu screen, images are copied to /usr/local/projects/numishare/images but are not attached to the numishare records. We are also getting a message 'Save Error. Are all required inputs filled?'

Do you have any suggestions on what might be causing this and how to resolve it? 

Thanks again for all your help on this install.

**Comment by jtstratford** [comment] 2020-08-28 16:44
Just to follow-up.  We updated our Numishare install to see if that helped this issue.  It worked fine otherwise but did not fix the Digital Representations problem.  We notice some other users reported having the same issue but could not see from the ticket exactly how they resolved it.  For example, https://github.com/ewg118/numishare/issues/44 although this appears to be a Windows install and we are running Ubuntu and Orbeon CE 2018.2.

Any guidance appreciated as we are trying to wrap up the installation for our son to use in the MPhil program at Oxford later next month.

**Comment by ewg118** [comment] 2020-08-28 17:04
I assume the NUDS record was saveable before you initiated the image upload?

Can you open numishare/xforms/nuds.xhtml and look for and make sure the following is uncommented:

    <fr:tab>
        <fr:label>Inspector</fr:label>
        <fr:xforms-inspector/>
    </fr:tab>

On the inspector tab, you can change the drop down menu for the instance to one called 'object', which is the NUDS document. Please try copying and pasting the NUDS document from this instance after trying to upload the image.

**Comment by jtstratford** [comment] 2020-08-28 21:13
Thanks for the reply.  Yes, the NUDS records are saveable.  It is just a problem with the local addition of the images.  For records imported from Mantis, the Digital Representations tab functions properly.

The code in nuds.xhtml is uncommented.

The Inspector tab is already set to object and if I understand your request correctly the code seems to be unchanged from before and after an image is uploaded.  If I misunderstand what you asked for, please let me know.

I attach the code and some screen shots to give you a better idea of what is going.

Again, many thanks.
[file2.txt](https://github.com/ewg118/numishare/files/5144209/file2.txt)
[mozilla.pdf](https://github.com/ewg118/numishare/files/5144210/mozilla.pdf)
[mozilla2.pdf](https://github.com/ewg118/numishare/files/5144211/mozilla2.pdf)
[mozilla3.pdf](https://github.com/ewg118/numishare/files/5144212/mozilla3.pdf)
[file1.txt](https://github.com/ewg118/numishare/files/5144213/file1.txt)

**Comment by jtstratford** [comment] 2020-09-02 18:20
One bit of additional information inn case it helps diagnose the issue we are having.

The Digital Represenations tab seems to work correctly for records imported from Mantis that already had images attached (see screen shot).  The problem is for coins that were imported without images or coin records created locally.

Any leads on how to resolve this are greatly appreciated.

[DigRepImport.pdf](https://github.com/ewg118/numishare/files/5164062/DigRepImport.pdf)

**Comment by ewg118** [comment] 2020-09-02 20:33
OK, I'm going to test this tomorrow. There has been a change in a version
of Orbeon sometime in 2018 or 2019 where the file:// protocol has some
security restrictions about read/write access to most of the filesystem.

**Comment by ewg118** [comment] 2020-09-03 14:38
I think I may have fixed this, but I can't fully verify it because I don't have a IIIF server running locally on my machine (i.e., the METS file element is inserted correctly, but the IIIF URL for the thumbnail is simply a dead link). You should grab the updated xforms/admin.xhtml, xforms, nuds.xhtml, and xforms/xbl/file-upload/file-upload.xbl. I may have found a mistake in the XML context for inserting the METS file element for the IIIF upload.

There are some other changes that need to be made in the Numishare config and the image folder location.

Beginning in a version of Orbeon from 2019 (I think), the file:// protocol no longer grants Orbeon complete access to read/write from every part of the filesystem. The file:// protocol can read from /tmp on the server, but the image location needs to be accessible with the oxf:/ protocol, which is shorthand for orbeon/WEB-INF/resources. For example, the upload mechanism puts the image file into a tomcat directory in /tmp, and then this file (with a random filename and .tmp extension) needs to be renamed and moved into a location Orbeon has write access to.

1. In the Numishare config, change the images/absolute_path to `oxf:/numishare-images`.
2. Create a folder anywhere on your filesystem you want to store the images.
3. Navigate to /path/to/orbeon/WEB-INF/resources and create a symlink called `numishare-images` that points to the folder you created above.
4. Ensure you've granted Tomcat read/write access to the folder.

Please let me know if this resolves the issue.

**Comment by jtstratford** [comment] 2020-09-04 18:48
I am hoping we can catch you for a quick question before the long weekend.

We substituted the xforms files per you instructions and that seemed to fix the appearance of the forms for Digital Representation but when we logged in the second time after backing up the virtual machine we are running on, the changes didn't seem to stick.  So, we need to recheck our work on that.

On the second part of your instructions regarding the image absolute path, can you specify exactly which file to edit. In other words the file name and path relative to the tomcat installation.

**Comment by ewg118** [comment] 2020-09-04 20:15
This is the Numishare project config.xml, which is stored in the eXist-db. You should be able to edit this by going to the Settings page for the tokens specimens project, go to the IIIF section and change the Image folder to `oxf:/numishare-images`

**Comment by jtstratford** [comment] 2020-09-06 21:52
Thanks for the new information.  

Per your message, we replaced the files
	xforms/admin.xhtml
	xforms/nuds.xhtml
	xforms/xbl/file-upload/file-upload.xbl

with the ones dated 9/4/2020 on github.  We also noticed that xforms/xbl/entity-input/entity-input.xbl had been updated so we replaced that as well.

We made sure permissions were the same as the old files and they are owned by tomcat.

We verified that our canteloup IIIF server was functioning by displaying an image from the folder using the test web address as noted in the canteloupe documentation (http://localhost:8182/iiif/2/image.tif/0,0,200,200/full/0/default.jpg)
We edited the numishare config in modify settings per your instructions (see screen shot) and created a symlink called numishare-admin to usr/local/projects/numishare/images and made tomcat the owner.

The problem persists (see screen shot) but we are nearly certain that the first time we displayed the Digital Representations tab after the changes, the boxes displayed correctly.  That led us to believe it could be a caching or similar problem so we emptied the browser cache and tried another browser but neither resolved the problem.  

We then went back to an earlier image of our virtual disk and made the same changes again but the problem persists and did not display correctly at any point. 

Further evidence that there may be a caching issue on the backend was that after logout of numishare admin and stopping and restarting tomcat, the admin credentials were still active and we were not prompted to login to numishare admin. Should we be looking at the cache for tomcat and/or orbeon? We are not sure how tomcat and orbeon handle the cache and so were nto sure how to proceed.

We are running tomcat 8.5 and orbeon CE

Any suggestions you might have as to how to proceed would be a great help.  Thanks again for your willingness to assist.
[screenshots.pdf](https://github.com/ewg118/numishare/files/5180354/screenshots.pdf)

**Comment by ewg118** [comment] 2020-09-08 14:27
Restarting Tomcat should invalidate any current logins and clear the cache, so I'm not sure what's happening. There the elements being added into the XML document after the image upload completes?

**Comment by jtstratford** [comment] 2020-09-08 17:21
The XML is the same because we cannot save after the attempted upload (see screenshots).

We use the Digital Representations IIIF upload and it shows the upload completed.  The files do move to \tomcat\temp but not to numishare-images which is owned by tomcat.  The Manual Upload does not provide a box so it doesn't function

We hope this information is helpful and appreciate all your assistance.

[ManualUpload.pdf](https://github.com/ewg118/numishare/files/5189916/ManualUpload.pdf)
[IIIFUpload (1).pdf](https://github.com/ewg118/numishare/files/5189917/IIIFUpload.1.pdf)

**Comment by ewg118** [comment] 2020-09-14 17:31
After selecting the jpg file for upload, Orbeon, I think reads the file headers from the browser, but you have to click the "Upload" button next to the filename/filesize text. The button then initiates the renaming/moving from /tmp to the correct location on the filesystem and inserts the METS elements into the XML document. The screenshot seems to indicate the "Upload" button wasn't clicked before clicking the Save button. Can you try that and let me know?

**Comment by jtstratford** [comment] 2020-09-14 20:42
We are selecting the files and then hitting upload.   They are moved with random names to the temp directory.  When we hit upload, they are moved to the numishare-image directory and renamed correctly, but we get a "Save Error" from the Create/Edit Coin screen, and we can only save and exit the record by "deleting" the images and the Digital Representations tab from the record.  The system does not delete the images from the numishare-images directory but they are not attached to the record either. 

Just in case it is relevant, the "Insert Images Manually" button doesn't work because no box is provided.

I hope that makes clearer what is happening and appreciate all the help.

**Comment by fgnm** [comment] 2021-05-20 11:03
I have a similar issue while using @Msch0150 Docker configuration. As IIIF Server it's used Loris, the server works, but whenever I try to upload an image it doesn't work.
Image upload returns 200 OK answer, also when click Upload button. But no file is moved into Loris directory, and I'm not able to save the coin becuase Numishare says there are missing fields.
Any hint?

**Comment by fgnm** [comment] 2021-05-20 14:05
To add more on the issue, I'm not able even to setup a manual uri for IIIF Server, looks like a Numishare bug:
![image](https://user-images.githubusercontent.com/5543339/118992515-01fbcc00-b985-11eb-9431-0426b3bb5d56.png)

**Comment by ewg118** [comment] 2021-05-20 15:03
This almost certainly fixes @jtstratford's issue also. Apologies for not looking more closely at this sooner. Aug/Sep 2020 was right in the middle finishing Hellenistic Royal Coinages.

**Comment by fgnm** [comment] 2021-05-20 15:59
Hi @ewg118 thanks for your answer, I can get now working manual uri for IIIF in Observe/Reverse mode (Combined mode still doesn't work, URI field is missing as like in the previuos image).
Upload seems not working, I'm running Numishare on Docker and that might be the cause of the issue.. I'm trying to fix but not able to get it working yet.
This is Orbeon config inside `docker-compose.yml`:
```
  orbeon:
    container_name: orbeon
    image: tiredofit/orbeon:latest
    ports:
      - "8081:8080"
    volumes:
      - "./orbeon.xml:/usr/local/tomcat/conf/Catalina/localhost/orbeon.xml"
      - "..:/usr/local/projects/numishare"
      - "..:/usr/local/tomcat/webapps/orbeon/WEB-INF/resources/apps/numishare"
      - "./exist-config.xml:/usr/local/tomcat/webapps/orbeon/WEB-INF/resources/apps/numishare/exist-config.xml"
      - "./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml"
      - "./web.xml:/usr/local/tomcat/webapps/orbeon/WEB-INF/web.xml"
      - "./properties-local.xml:/usr/local/tomcat/webapps/orbeon/WEB-INF/resources/config/properties-local.xml"
      - "./admin.xhtml:/usr/local/tomcat/webapps/orbeon/WEB-INF/resources/apps/numishare/xforms/admin.xhtml"
      - "../../../data/docker-loris-data/images:/usr/local/tomcat/webapps/orbeon/WEB-INF/resources/numishare-images"
```
I've add the list line to link numishare-images path to Loris folder, that folder has for now permissions set to 777 in order to avoid any possibile issue.. Have you some suggestions?

**Comment by ewg118** [comment] 2021-05-20 16:23
I fixed the combined image IIIF service URL.

When you click the Upload button, is the file being written into /tmp. In /tmp, look for .tmp files named xforms_upload.*, or see if there are any files with this name in a subfolder for tomcat in /tmp.

**Comment by fgnm** [comment] 2021-05-20 16:51
Thanks for the combined fix, I've checked the /temp directory and file is not uploaded at all even before and after pressing `Upload` button.

**Comment by ewg118** [comment] 2021-05-20 17:39
I'm not sure if this is Docker related or not. In theory, Tomcat should be able to write into /tmp on the server regardless of whether it was deployed in Docker. @Msch0150. The upload button functions by moving the file you uploaded, which was arbitrarily renamed by Orbeon and put into /tmp somewhere, into the oxf:/numishare-images folder with a new, consistent filename. If the uploaded file isn't being written into /tmp, then it can't be moved to its final destination.

Is there anything in the orbeon log?

**Comment by Msch0150** [comment] 2021-05-20 19:35
Info:
Currently I am using the IIIF in the following way:

The images directory is created via the setup.sh:

mkdir -p ${HOME}/data/docker-loris-data/images

The compose file maps the directory:

iiif:
    image: lorisimageserver/loris
    container_name: numishare_iiif
    #build: ./loris
    volumes:
      - ../../../data/docker-loris-data/images:/opt/loris/tests/img
    ports:
      - "10206:5004"


I copy the images directly into a data directory of the iiif container based on the collection:

cp <source-dir>/*.jpg ${HOME}/data/docker-loris-data/images/<my_collection_name>/jpg/

So that cp command is executed outside the container.
Before I upload my coin-data-nuds.xml file to the exist-db, I add the following data to the xml-structure by a program:

<ns0:digRep>
<ns3:fileSec>
<ns3:fileGrp USE="obverse">
<ns3:file USE="iiif">
<ns3:FLocat LOCYPE="URL" ns2:href="http://localhost:10206/srm/jpg/srm.20081212-002.1.jpg"/>
</ns3:file>
<ns3:file USE="archive" MIMETYPE="image/jpeg">
<ns3:FLocat LOCYPE="URL" ns2:href="http://localhost:10206/srm/jpg/srm.20081212-002.1.jpg/full/full/0/default.jpg"/>
</ns3:file>
<ns3:file USE="reference" MIMETYPE="image/jpeg">
<ns3:FLocat LOCYPE="URL" ns2:href="http://localhost:10206/srm/jpg/srm.20081212-002.1.jpg/full/350,/0/default.jpg"/>
</ns3:file>
<ns3:file USE="thumbnail" MIMETYPE="image/jpeg">
<ns3:FLocat LOCYPE="URL" ns2:href="http://localhost:10206/srm/jpg/srm.20081212-002.1.jpg/full/175,/0/default.jpg"/>
</ns3:file>
</ns3:fileGrp>
<ns3:fileGrp USE="reverse">
<ns3:file USE="iiif">
<ns3:FLocat LOCYPE="URL" ns2:href="http://localhost:10206/srm/jpg/srm.20081212-002.2.jpg"/>
</ns3:file>
<ns3:file USE="archive" MIMETYPE="image/jpeg">
<ns3:FLocat LOCYPE="URL" ns2:href="http://localhost:10206/srm/jpg/srm.20081212-002.2.jpg/full/full/0/default.jpg"/>
</ns3:file>
<ns3:file USE="reference" MIMETYPE="image/jpeg">
<ns3:FLocat LOCYPE="URL" ns2:href="http://localhost:10206/srm/jpg/srm.20081212-002.2.jpg/full/350,/0/default.jpg"/>
</ns3:file>
<ns3:file USE="thumbnail" MIMETYPE="image/jpeg">
<ns3:FLocat LOCYPE="URL" ns2:href="http://localhost:10206/srm/jpg/srm.20081212-002.2.jpg/full/175,/0/default.jpg"/>
</ns3:file>
</ns3:fileGrp>
</ns3:fileSec>
</ns0:digRep>

So, right now I am not using the numishare UI for digital representation.

Info: my Tomcat (orbeon) container has no filesystem connection to the IIIF (loris) container.

Anyhow, I willl try to check what is happening during the upload in /tmp on Tomcat tomorrow.

**Comment by Msch0150** [comment] 2021-05-21 06:43
(info: overlooked the entry from fgnm  in the docker-compose.xml: 
      - "../../../data/docker-loris-data/images:/usr/local/tomcat/webapps/orbeon/WEB-INF/resources/numishare-images"
which looks fine for me.)

So far only a small step ahead:

It looks like that numshare places the image file after the selection to the tmp dir of the JVM. Try to check it in your container:

```
docker exec -ti orbeon /bin/bash
ps -ef | grep java
```

Check in the output the value of `-Djava.io.tmpdir`. In my case it looks like:
`-Djava.io.tmpdir=/usr/local/tomcat/temp`

After seletcting the file for the upload in the numishare UI, I can see the file on the filesystem:

```
ls -ltrau /usr/local/tomcat/temp
total 6164
-rw-r--r-- 1 root root       0 May  5  2020 safeToDelete.tmp
drwxr-xr-x 1 root root    4096 May 21 05:27 ..
drwxr-x--- 3 root root    4096 May 21 05:37 orbeon
drwxr-xr-x 2 root root    4096 May 21 05:51 nix
-rw-r----- 1 root root 6291456 May 21 06:20 xforms_upload_9436807752789513236.tmp
drwxrwxrwx 1 root root    4096 May 21 06:20 .
```

So, in my case `xforms_upload_9436807752789513236.tmp`.

But when I click Upload the file will stay in the directory and no changes in the target directory:

`/usr/local/tomcat/webapps/orbeon/WEB-INF/resources/numishare-images/`

Info: the directory `/usr/local/tomcat/webapps/orbeon/WEB-INF/resources/numishare-images/` was created manually in the container and I set the rights (for a test to rwxrwxrwx). I add the directory in the Numishare UI settings in the section IIF Image Server as the value for "Images Folder" with a leading /.

Hm. The orbeon.log shows after clicking "Upload":

```
2021-05-21 06:32:11,600 INFO  lifecycle  - event: {"request": "402", "session": "818BC9E0A0F584817F634ADCA0871318", "source": "limiter", "message": "start: filter", "path": "/xforms-server", "method": "POST"}
2021-05-21 06:32:11,600 INFO  lifecycle  - event: {"request": "402", "session": "818BC9E0A0F584817F634ADCA0871318", "source": "limiter", "message": "start: chain", "path": "/xforms-server", "method": "POST", "wait": "0"}
2021-05-21 06:32:11,601 INFO  lifecycle  - event: {"request": "402", "session": "818BC9E0A0F584817F634ADCA0871318", "source": "service", "message": "start: handle"}
2021-05-21 06:32:11,601 INFO  ProcessorService  - /xforms-server - Received request
2021-05-21 06:32:11,636 INFO  lifecycle  - event: {"request": "402", "session": "818BC9E0A0F584817F634ADCA0871318", "source": "xforms", "message": "ajax with update events", "uuid": "e0d0bc186e7a86fc1665bd359925a86b1cda48e8"}
2021-05-21 06:32:11,636 INFO  lifecycle  - event: {"request": "402", "session": "818BC9E0A0F584817F634ADCA0871318", "source": "xforms", "message": "before document lock", "uuid": "e0d0bc186e7a86fc1665bd359925a86b1cda48e8"}
2021-05-21 06:32:11,636 INFO  lifecycle  - event: {"request": "402", "session": "818BC9E0A0F584817F634ADCA0871318", "source": "xforms", "message": "got document lock", "path": "/xforms-server", "method": "POST", "uuid": "e0d0bc186e7a86fc1665bd359925a86b1cda48e8", "wait": "0"}
2021-05-21 06:32:11,687 WARN  XFormsServer  - xxf:instance() - instance not found {instance id: "fr-xforms-inspector-input"}
2021-05-21 06:32:11,711 INFO  lifecycle  - event: {"request": "402", "session": "818BC9E0A0F584817F634ADCA0871318", "source": "xforms", "message": "after cacheOrStore", "document cache current size": "26", "document cache max size": "50"}
2021-05-21 06:32:11,711 INFO  ProcessorService  - /xforms-server - Timing: 110
2021-05-21 06:32:11,712 INFO  lifecycle  - event: {"request": "402", "session": "818BC9E0A0F584817F634ADCA0871318", "source": "service", "message": "end: handle", "time": "111 ms"}
2021-05-21 06:32:11,712 INFO  lifecycle  - event: {"request": "402", "session": "818BC9E0A0F584817F634ADCA0871318", "source": "limiter", "message": "end: chain", "time": "112 ms"}
2021-05-21 06:32:11,712 INFO  lifecycle  - event: {"request": "402", "session": "818BC9E0A0F584817F634ADCA0871318", "source": "limiter", "message": "end: filter", "time": "112 ms"}
2021-05-21 06:32:11,831 INFO  lifecycle  - event: {"request": "403", "session": "818BC9E0A0F584817F634ADCA0871318", "source": "limiter", "message": "start: filter", "path": "/xforms-server", "method": "POST"}
2021-05-21 06:32:11,831 INFO  lifecycle  - event: {"request": "403", "session": "818BC9E0A0F584817F634ADCA0871318", "source": "limiter", "message": "start: chain", "path": "/xforms-server", "method": "POST", "wait": "0"}
2021-05-21 06:32:11,832 INFO  lifecycle  - event: {"request": "403", "session": "818BC9E0A0F584817F634ADCA0871318", "source": "service", "message": "start: handle"}
2021-05-21 06:32:11,832 INFO  ProcessorService  - /xforms-server - Received request
2021-05-21 06:32:11,837 INFO  lifecycle  - event: {"request": "403", "session": "818BC9E0A0F584817F634ADCA0871318", "source": "xforms", "message": "ajax with update events", "uuid": "e0d0bc186e7a86fc1665bd359925a86b1cda48e8"}
2021-05-21 06:32:11,837 INFO  lifecycle  - event: {"request": "403", "session": "818BC9E0A0F584817F634ADCA0871318", "source": "xforms", "message": "before document lock", "uuid": "e0d0bc186e7a86fc1665bd359925a86b1cda48e8"}
2021-05-21 06:32:11,837 INFO  lifecycle  - event: {"request": "403", "session": "818BC9E0A0F584817F634ADCA0871318", "source": "xforms", "message": "got document lock", "path": "/xforms-server", "method": "POST", "uuid": "e0d0bc186e7a86fc1665bd359925a86b1cda48e8", "wait": "0"}
2021-05-21 06:32:11,841 INFO  lifecycle  - event: {"request": "403", "session": "818BC9E0A0F584817F634ADCA0871318", "source": "xforms", "message": "after cacheOrStore", "document cache current size": "26", "document cache max size": "50"}
2021-05-21 06:32:11,841 INFO  ProcessorService  - /xforms-server - Timing: 9
2021-05-21 06:32:11,842 INFO  lifecycle  - event: {"request": "403", "session": "818BC9E0A0F584817F634ADCA0871318", "source": "service", "message": "end: handle", "time": "10 ms"}
2021-05-21 06:32:11,842 INFO  lifecycle  - event: {"request": "403", "session": "818BC9E0A0F584817F634ADCA0871318", "source": "limiter", "message": "end: chain", "time": "11 ms"}
2021-05-21 06:32:11,842 INFO  lifecycle  - event: {"request": "403", "session": "818BC9E0A0F584817F634ADCA0871318", "source": "limiter", "message": "end: filter", "time": "11 ms"}
```

Does it look OK? 

Info: no useful entries in catalina.log or access.log

Two  questions:
1.
Is my assumption correct that the base URL for the IIIF Image Server (in Numishare Settings) is only used to construct the links to the object for the presentation and is not used for the upload of the images?
2.
The default value for the Image folder is `oxf:/numishare-images`. If I leave it as it is and add the URL for the IIF Server then I am not able to save the config until I enter an absolute path like `/usr/local/tomcat/webapps/orbeon/WEB-INF/resources/numishare-images/`. Is that behaviour correct or wanted?

**Comment by fgnm** [comment] 2021-05-21 08:31
I can confirm that the upload happens to `/usr/local/tomcat/temp` directory inside Docker container, so in my `docker-compose.yml` I've add this settings to change temp directory with env variable:
```
  orbeon:
    container_name: orbeon
    image: tiredofit/orbeon:latest
    ports:
      - "8081:8080"
    environment:
      - CATALINA_TMPDIR=/tmp
    volumes:
      - "./orbeon.xml:/usr/local/tomcat/conf/Catalina/localhost/orbeon.xml"
      - "..:/usr/local/projects/numishare"
      - "..:/usr/local/tomcat/webapps/orbeon/WEB-INF/resources/apps/numishare"
      - "./exist-config.xml:/usr/local/tomcat/webapps/orbeon/WEB-INF/resources/apps/numishare/exist-config.xml"
      - "./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml"
      - "./web.xml:/usr/local/tomcat/webapps/orbeon/WEB-INF/web.xml"
      - "./properties-local.xml:/usr/local/tomcat/webapps/orbeon/WEB-INF/resources/config/properties-local.xml"
      - "./admin.xhtml:/usr/local/tomcat/webapps/orbeon/WEB-INF/resources/apps/numishare/xforms/admin.xhtml"
      - "../../../data/docker-loris-data/images:/usr/local/tomcat/webapps/orbeon/WEB-INF/resources/numishare-images"
```
Now files are correctly uploaded into `/tmp` directory, but when press `Upload` button the file stays there and not moved to the `numishare-images` directory.

**Comment by ewg118** [comment] 2021-05-24 14:58
I think we'll have to take a look at the underlying Orbeon pipelines that read the file from your tmp directory and move it to the designated location. The tmp location isn't hardcoded within the Numishare code anywhere; it's entirely dependent on the tmp folder that Orbeon reads from the Java options for Tomcat.

First, open xforms/nuds.xhtml and scroll down to line [2369](https://github.com/ewg118/numishare/blob/master/xforms/nuds.xhtml#L2369). Comment out the xforms:groups and copy and paste the `<numishare:file-upload/>` so that it will always display after any condition.

![Screenshot from 2021-05-24 10-43-25](https://user-images.githubusercontent.com/563187/119364906-69fc2c00-bc7d-11eb-91b6-6fe21144713e.png)

Then open xforms/xbl/file-upload/file-upload.xbl and go to line [235](https://github.com/ewg118/numishare/blob/master/xforms/xbl/file-upload/file-upload.xbl#L235) and uncomment the `<fr:xforms-inspector/>`. 

Reload the form and then add in the obverse/reverse images. There will be a UI that shows the underlying XForms instances with all of the data models. Upload an obverse image, and then change the drop-down menu in the inspector to the model to something named like "file upload model 1". 

There are several instances in this XBL component that capture the tmp filename, and then use that as the basis for moving it from the tmp folder with the arbitrary filename to your specified `oxf:/numishare-images` at a filename based on the ID number + side. There's the `file` instance that underlies the upload widget itself, and then the `generator-config` and `serializer-config` instances that are the source and destination for moving the file to the IIIF folder. The "Upload" button triggers the upload that populates the `file` instead and then triggers the file move with the second two instances. There must be some disconnect here. Please check that the path in the `file` instance is the same as the path in the `generator-config` url element.

![Screenshot from 2021-05-24 10-42-23](https://user-images.githubusercontent.com/563187/119366415-f22f0100-bc7e-11eb-8b3d-9be8135c3c1e.png)

![Screenshot from 2021-05-24 10-42-33](https://user-images.githubusercontent.com/563187/119366423-f529f180-bc7e-11eb-8ca6-92e4244b37b5.png)

**Comment by Msch0150** [comment] 2021-05-24 18:21
I followed your instructions.
I could see that the "serializer-config showed something like:

<url>/usr/local/tomcat/temp//470b27b8d8.com.jpg</url>

Info: "/usr/local/tomcat/temp/" is the value of "Image Folder" in the IIIF Settings in the UI.

But the generator showed someting like <url>file:/usr/local/tomcat/temp/xforms_upload...</url>.
So I made a small test and changed in "config.xml" the value for "absolute_path" manually to:

					<images>
						<absolute_path>file:/usr/local/tomcat/temp</absolute_path>
						<iiif_server>http://localhost:10206/</iiif_server>

Now it seems to work. After trying to upload the file, it appears in /usr/local/tomcat/temp as:

"/usr/local/tomcat/temp/470b27b8d8.com.jpg"

So (my) remaining issue is then how to change the Image Folder in the UI.
The UI won't let me save the config changes.

@fgnm : Are, you able change the "Image Folder" to "file:/usr/local/tomcat/temp" or something similar with a prepending "file:" in the UI?

**Comment by ewg118** [comment] 2021-05-24 18:42
Is there anything else possibly invalid in the config that would prohibit it from saving? There's nothing about your iiif_server or absolute_path value that is invalid. Try pulling the latest settings.xhtml from Github. I may have fixed some problems with validation in the last few months.

Due to some updates to the security in Orbeon, the app is only capable of writing to the Tomcat designated temp folder or orbeon/WEB-INF/resources. So if you can write the uploaded file into the temp folder but not orbeon/WEB-INF/resources/numishare-images (also referred to by `oxf:/numishare-images` in Orbeon), it still seems like a read-write permission error of the folder. I'm not sure why this would persist after setting `chmod 777` on it.

Ethan

**Comment by Msch0150** [comment] 2021-05-25 19:16
Info: I opened #104 for the "save" issue.

**Comment by ewg118** [comment] 2021-05-27 16:37
"oxf:/numishare-images" should work, so I'm surprised that it does not. The second and third options shouldn't work, so that seems correct. The fourth option may work on older versions of Orbeon. Do you know which one is deployed in Docker?

`oxf:/` is merely shorthand for `$ORBEON_HOME/WEB-INF/resources`, which has always been the case. XPL calls within the XForms engine use the oxf:/ protocol, e.g., `oxf:/apps/numishare/xpl/get-authentication.xpl`.

**Comment by Msch0150** [comment] 2021-05-27 18:35
As far as I can see: 2019.2.0.201912301747 CE
Is it an "older" one? The latest is 2020.1.3. Which one are you using?

**Comment by ewg118** [comment] 2021-05-27 18:48
Probably also a 2019 edition. I guess if `file:/usr/local/tomcat/webapps/orbeon/WEB-INF/resources/numishare-images` works, then just go with it.

**Comment by fgnm** [comment] 2021-05-28 07:26
Thanks @Msch0150 and @ewg118 for the help, setting `file:/usr/local/tomcat/webapps/orbeon/WEB-INF/resources/numishare-images` worked! It also works IIIF with mounted volume in docker.

**Comment by ewg118** [comment] 2021-06-01 19:15
OK, great. I'm going to close this issue then.

**Closed by ewg118** 2021-06-01 19:15 UTC
